PREFIX owl:  <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
CONSTRUCT {
	?nClass a owl:Class .
}
WHERE {
	{
		?nClass a rdfs:Class .
	} UNION {
		?nClass rdfs:subClassOf ?nOtherClass .
	} UNION {
		?nOtherClass rdfs:subClassOf ?nClass .
	}
	FILTER (?nClass != owl:Ontology)
	FILTER (?nClass != rdfs:Class)
	FILTER (?nClass != rdfs:Resource)
}
